version: '3'
services:
    zk1:
        image: zookeeper
        logging:
            driver: "json-file"
            options:
               max-size: "10m"
               max-file: 3
        networks:
            - net
        ports:
            - 2181:2181
        environment:
            ZOO_MY_ID: 1
            ZOO_SERVERS: server.1=0.0.0.0:2888:3888 server.2=zk2:2888:3888 server.3=zk3:2888:3888

    zk2:
        image: zookeeper
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: 3
        networks:
            - net
        ports:
            - 2182:2181
        environment:
            ZOO_MY_ID: 2
            ZOO_SERVERS: server.1=zk1:2888:3888 server.2=0.0.0.0:2888:3888 server.3=zk3:2888:3888

    zk3:
        image: zookeeper
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: 3
        networks:
            - net
        ports:
            - 2183:2181
        environment:
            ZOO_MY_ID: 3
            ZOO_SERVERS: server.1=zk1:2888:3888 server.2=zk2:2888:3888 server.3=0.0.0.0:2888:3888

    kafka:
        deploy:
            mode: global
        image: wurstmeister/kafka
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: 3
        environment:
            KAFKA_ADVERTISED_PORT: 9092
            KAFKA_ZOOKEEPER_CONNECT: zk1:2181,zk2:2181,zk3:2181
            KAFKA_HEAP_OPTS: -Xmx256M -Xms128M
            KAFKA_RESERVED_BROKER_MAX_ID: 1001
            KAFKA_BROKER_ID: 1001
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - net
            - kafka-net
        ports:
            - 9092:9092
    kafka-manager:
        image: sheepkiller/kafka-manager:latest
        ports:
            - 10000:9000
        networks:
            - net
            - kafka-net
        links:
            - zk1
            - zk2
            - zk3
            - kafka
        environment:
            ZK_HOSTS: zk1:2181,zk2:2181,zk3:2181
            APPLICATION_SECRET: qwe123
            KM_ARGS: -Djava.net.preferIPv4Stack=true
networks:
    net:
        driver: overlay
        driver_opts:
           encrypted: "true"

    kafka-net:
        external:
            name: kafka-net
